---
- hosts: satellite
  roles:
    - satellite_prep
    - satellite_prep_rhv

- hosts: rhv-engine
  roles:
    - distribute_ssh_keys

- hosts: rhv-hypervisors
  roles:
    - distribute_ssh_keys

- include: deploy_rhv.yml

- hosts: satellite
  roles:
    - satellite_post_rhv