- name: Check product exists already
  command: >-
    hammer --output json -u "{{ sat_admin_user }}" -p "{{ sat_admin_password}}"
    product info --name "{{ product_name }}" --organization "{{ org_name }}"
  register: product_output
  ignore_errors: True
  changed_when: False
  failed_when: product_output|failed and not 'not found' in product_output.stderr

- name: Create product
  command: >-
    hammer --output json -u "{{ sat_admin_user }}" -p "{{ sat_admin_password}}"
    product create --name "{{ product_name }}" --organization "{{ org_name }}"
  when: product_output|failed and 'not found' in product_output.stderr
