---
- include: create-product.yml
- include: create-repo.yml repo={{item}}
  with_items:  "{{fusor_repositories}}"
- include: create-content-view.yml name="Fusor Puppet Content"
# Todo Access Insights
#- include: import-puppet-classes.yml
#  with_items: "{{fusor_puppet_classes}}"
- include: publish-content-view.yml name="Fusor Puppet Content" version=1

