- name: Check if repository is enabled already
  command: >
    hammer --output json -u "{{ config.satellite.admin_user }}" -p "{{ config.satellite.admin_password}}"
    repository info
    --organization "{{ config.satellite.default_org_name }}"
    --product "{{ repo.product }}"
    --name "{{ repo.full_name }}"
  register: repo_output
  ignore_errors: True
  changed_when: False
  failed_when: repo_output|failed and not 'not found' in repo_output.stderr


- name: Enable repository
  command: >
    hammer --output json -u "{{ config.satellite.admin_user }}" -p "{{ config.satellite.admin_password}}"
    repository-set enable
    --organization "{{ config.satellite.default_org_name }}"
    --product "{{ repo.product }}"
    {% if repo.releasever is defined %}--releasever "{{ repo.releasever }}"{% endif %}
    --basearch "{{ repo.basearch}}"
    --name "{{ repo.name }}"
  when: repo_output|failed and 'not found' in repo_output.stderr
