---
- include: create_product.yml
  vars:
    name: "{{config.fusor.product_name}}"

- include: create_repo.yml repo={{item}}
  with_items:  "{{ fusor_repositories }}"

- include: create_content_view.yml name={{config.fusor.puppet_content_view_name}}

# Todo Access Insights
#- include: import_puppet_classes.yml
#  with_items: "{{ fusor_puppet_classes }}"

- include: publish_content_view.yml
  vars:
    name: "{{config.fusor.puppet_content_view_name}}"
    version: 1

- include: enable_repo.yml
  vars:
    repo: "{{ item }}"
  with_items:  "{{ required_repositories }}"

- include: sync_repos.yml
    repos: "{{ required_repositories }}"

- include: create_fusor_hostgroup.yml

