- name: Get version of content-view
  command: >
    hammer --output json -u "{{ config.satellite.admin_user }}" -p "{{ config.satellite.admin_password}}"
    content-view info
    --organization "{{ config.satellite.default_org_name }}"
    --name "{{ name }}"
  register: cv_output
  changed_when: False

- set_fact:
    cv: "{{ cv_output.stdout | from_json }}"
  changed_when: False

- set_fact:
    versions_dict: "{{ cv['Versions'] }}"
  changed_when: False
  when: cv is defined

- set_fact:
    max_version: "{{ versions_dict.values() | map(attribute='Version') | list | map('float') | list | max }}"
  when: versions_dict is defined and versions_dict.values()

- name: Publish content-view
  command: >
    hammer --output json -u "{{ config.satellite.admin_user }}" -p "{{ config.satellite.admin_password}}"
    content-view publish
    --organization "{{ config.satellite.default_org_name }}"
    --name "{{ name }}"
  when: "{{ version is undefined or max_version is undefined or max_version < version }}"
