---
- hosts: satellite

  remote_user: vagrant

  tasks:
  - name: Check existing Satellite org for Fusor org
    shell: hammer --output json -u "{{ sat_admin_user }}" -p "{{ sat_admin_password}}" discovery list
    register: discovered_hosts_raw

  - name: load json
    set_fact:
      discovered_hosts: '{{ discovered_hosts_raw.stdout | from_json }}'

  - name: echo discovered hosts
    debug: msg={{ item['ID'] }}
    with_items: "{{ discovered_hosts }}"
